[package]
name = "aesify"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
argon2 = "0.5"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"
anyhow = "1.0"
zip = "0.6"
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.2"
